name: Publish GitHub Pages and NPM

on:
    push:

permissions:
    contents: write

jobs:
    publish-gh-pages:
        runs-on:
            - ubuntu-latest

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v4

            - name: Install Node.js, NPM and Yarn
              uses: actions/setup-node@v4
              with:
                  node-version: 20.17.0

            - name: Build Site
              run: |
                  npm i
                  npm run build
                  cd example
                  npm i
                  npm run build
                  cd

            - uses: actions/upload-artifact@v3
              with:
                  path: example/dist
            - uses: actions/upload-pages-artifact@v1
              with:
                  path: example/dist

    deploy:
        needs: build
        runs-on: ubuntu-latest 
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        permissions:
            pages: write
            id-token: write
        steps:
            - uses: actions/deploy-pages@v1
            id: deployment